<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Invoice Cash Report</title><style>body{font:14px system-ui;margin:2rem;color:#18212f}.filter,table{width:100%;border-collapse:collapse;margin:1rem 0}td,th{border:1px solid #d7dce3;padding:.6rem;text-align:left}th{background:#f4f6f8}input,button{padding:.5rem}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1rem}.card{border:1px solid #d7dce3;padding:1rem}.total{font-weight:700}</style></head>
<body>
<h1>Invoice Cash Report</h1>
<form method="get" action="{{ route('composer-rumus.cash.search') }}"><table class="filter"><tr><td><label>From <input type="date" name="start_date" value="{{ $start->toDateString() }}" required></label></td><td><label>To <input type="date" name="end_date" value="{{ $end->toDateString() }}" required></label></td><td><button>Search</button></td></tr></table></form>
<h2>Payments</h2><table><thead><tr><th>#</th><th>Invoice</th><th>Customer</th><th>Payment date</th><th>Method</th><th>Amount</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $loop->iteration }}</td><td>{{ $payment->invoice->invoice_no ?? $payment->invoice_id }}</td><td>{{ $payment->invoice->customer->name ?? '-' }}</td><td>{{ $payment->payment_date }}</td><td>{{ $payment->transaction->transaction_name ?? $payment->payment_method }}</td><td>{{ number_format($payment->amount, 2) }}</td></tr>@empty<tr><td colspan="6">No payments found.</td></tr>@endforelse</tbody></table>
<div class="cards"><section class="card"><h2>Payment methods</h2><table><thead><tr><th>Method</th><th>Payments</th><th>Amount</th></tr></thead><tbody>@foreach($summary as $method => $data)<tr><td>{{ $method }}</td><td>{{ $data['count'] }}</td><td>{{ number_format($data['total'], 2) }}</td></tr>@endforeach</tbody></table></section><section class="card"><h2>Expenses</h2><table><thead><tr><th>Method</th><th>Items</th><th>Amount</th></tr></thead><tbody>@forelse($expenseSummary as $method => $data)<tr><td><a href="{{ route('composer-rumus.cash.expenses', ['method' => $method, 'start_date' => $start->toDateString(), 'end_date' => $end->toDateString()]) }}">{{ $method }}</a></td><td>{{ $data['count'] }}</td><td>{{ number_format($data['total'], 2) }}</td></tr>@empty<tr><td colspan="3">No expenses found.</td></tr>@endforelse</tbody></table></section></div>
<h2>Profit summary</h2><table><thead><tr><th>Method</th><th>Income</th><th>Expense</th><th>Profit</th></tr></thead><tbody>@foreach($profitSummary as $method => $data)<tr><td>{{ $method }}</td><td>{{ number_format($data['income_total'], 2) }}</td><td>{{ number_format($data['expense_total'], 2) }}</td><td>{{ number_format($data['profit'], 2) }}</td></tr>@endforeach</tbody></table>
</body></html>
